### PR TITLE
Update and rename star-rating_locale_LANG.js to star-rating_locale_pt…

### PR DESCRIPTION
**Pull request by sio-iago**
…BR.js

### CODE REVIEW

**Comment by kartik-v** [comment]
Do not rename `star_rating_locale_LANG.js` file... just copy it and create a new renamed file for your locale.

**Comment by vtrmantovani** [comment]
+1

**Comment by kartik-v** [comment]
Closed via #89.

**Comment by sio-iago** [comment]
Thanks man. I was out of time to fix that, my bad.

**Pull request closed without merging**
